// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunTrackerV5App.Data;

#nullable disable

namespace RunTrackerV5App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325203713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("RunTrackerV5App.Models.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DistanceMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
